export const guests = [
    "Friend 1",
    "Friend 2",
    "Friend 3",
    "Friend 4",
    "Friend 5",
    "Friend 6",
    "Friend 7",
    "Friend 8",
    "Friend 9",
    "Friend 10",
    "Friend 11",
    "Friend 12",
    "Friend 13",
    "Friend 14",
    "Friend 15",
    "Friend 16",
];
