export const guests = [
    "Rama Manasseri",
    "Mou Del Grecco",
    "Diego Maciel",
    "Pocho",
    "Sassy",
    "Juli Mattos",
    "Manitas",
    "Yankee",
    "Cristian Tresalli",
    "Cronos",
    "Boty",
    "Lara Golzman",
    "Primavera",
    "Juan Ríos",
    "Manu Slamerón",
    "Leo Burundanga",
    "Emi Dominguez",
    "Franquito Azari",
    "Seba Maldonado",
    "Ceci Saavedra",
    "Lola Vicente",
    "Agus 💗",
    "Mamá",
    "Papá",
    "Celi",
    "Betty",
    "Nico Fina",
    "Lisi Fina",
    "Juli Fina",
    "German Fina",
    "Mari",
];